// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.9.1
// source: daqpb.proto

package daqproto

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//    enum DataPointID {
	//        VELOCITY = 0;
	//        COORDINATES = 1;
	//        TPRATE = 2;
	//        ENGPRESSURE = 3;
	//    }
	DataPointID uint32 `protobuf:"varint,1,opt,name=DataPointID,proto3" json:"DataPointID,omitempty"`
	// Types that are assignable to DataPoint:
	//	*Packet_Velocity
	//	*Packet_Coordinate
	//	*Packet_TurboPumpRMP
	//	*Packet_EnginePressure
	DataPoint isPacket_DataPoint `protobuf_oneof:"DataPoint"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daqpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_daqpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_daqpb_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetDataPointID() uint32 {
	if x != nil {
		return x.DataPointID
	}
	return 0
}

func (m *Packet) GetDataPoint() isPacket_DataPoint {
	if m != nil {
		return m.DataPoint
	}
	return nil
}

func (x *Packet) GetVelocity() *Packet_DPvelocity {
	if x, ok := x.GetDataPoint().(*Packet_Velocity); ok {
		return x.Velocity
	}
	return nil
}

func (x *Packet) GetCoordinate() *Packet_DPcoordinate {
	if x, ok := x.GetDataPoint().(*Packet_Coordinate); ok {
		return x.Coordinate
	}
	return nil
}

func (x *Packet) GetTurboPumpRMP() *Packet_DPTurboPumpRMP {
	if x, ok := x.GetDataPoint().(*Packet_TurboPumpRMP); ok {
		return x.TurboPumpRMP
	}
	return nil
}

func (x *Packet) GetEnginePressure() *Packet_DPEnginePRE {
	if x, ok := x.GetDataPoint().(*Packet_EnginePressure); ok {
		return x.EnginePressure
	}
	return nil
}

type isPacket_DataPoint interface {
	isPacket_DataPoint()
}

type Packet_Velocity struct {
	Velocity *Packet_DPvelocity `protobuf:"bytes,2,opt,name=velocity,proto3,oneof"`
}

type Packet_Coordinate struct {
	Coordinate *Packet_DPcoordinate `protobuf:"bytes,3,opt,name=coordinate,proto3,oneof"`
}

type Packet_TurboPumpRMP struct {
	TurboPumpRMP *Packet_DPTurboPumpRMP `protobuf:"bytes,4,opt,name=turboPumpRMP,proto3,oneof"`
}

type Packet_EnginePressure struct {
	EnginePressure *Packet_DPEnginePRE `protobuf:"bytes,5,opt,name=enginePressure,proto3,oneof"`
}

func (*Packet_Velocity) isPacket_DataPoint() {}

func (*Packet_Coordinate) isPacket_DataPoint() {}

func (*Packet_TurboPumpRMP) isPacket_DataPoint() {}

func (*Packet_EnginePressure) isPacket_DataPoint() {}

type Packet_DPvelocity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Velx float32 `protobuf:"fixed32,1,opt,name=velx,proto3" json:"velx,omitempty"`
	Vely float32 `protobuf:"fixed32,2,opt,name=vely,proto3" json:"vely,omitempty"`
	Velz float32 `protobuf:"fixed32,3,opt,name=velz,proto3" json:"velz,omitempty"`
}

func (x *Packet_DPvelocity) Reset() {
	*x = Packet_DPvelocity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daqpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet_DPvelocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet_DPvelocity) ProtoMessage() {}

func (x *Packet_DPvelocity) ProtoReflect() protoreflect.Message {
	mi := &file_daqpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet_DPvelocity.ProtoReflect.Descriptor instead.
func (*Packet_DPvelocity) Descriptor() ([]byte, []int) {
	return file_daqpb_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Packet_DPvelocity) GetVelx() float32 {
	if x != nil {
		return x.Velx
	}
	return 0
}

func (x *Packet_DPvelocity) GetVely() float32 {
	if x != nil {
		return x.Vely
	}
	return 0
}

func (x *Packet_DPvelocity) GetVelz() float32 {
	if x != nil {
		return x.Velz
	}
	return 0
}

type Packet_DPcoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coorx float32 `protobuf:"fixed32,1,opt,name=coorx,proto3" json:"coorx,omitempty"`
	Coory float32 `protobuf:"fixed32,2,opt,name=coory,proto3" json:"coory,omitempty"`
	Coorz float32 `protobuf:"fixed32,3,opt,name=coorz,proto3" json:"coorz,omitempty"`
}

func (x *Packet_DPcoordinate) Reset() {
	*x = Packet_DPcoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daqpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet_DPcoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet_DPcoordinate) ProtoMessage() {}

func (x *Packet_DPcoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_daqpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet_DPcoordinate.ProtoReflect.Descriptor instead.
func (*Packet_DPcoordinate) Descriptor() ([]byte, []int) {
	return file_daqpb_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Packet_DPcoordinate) GetCoorx() float32 {
	if x != nil {
		return x.Coorx
	}
	return 0
}

func (x *Packet_DPcoordinate) GetCoory() float32 {
	if x != nil {
		return x.Coory
	}
	return 0
}

func (x *Packet_DPcoordinate) GetCoorz() float32 {
	if x != nil {
		return x.Coorz
	}
	return 0
}

type Packet_DPTurboPumpRMP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rpm float32 `protobuf:"fixed32,1,opt,name=rpm,proto3" json:"rpm,omitempty"`
}

func (x *Packet_DPTurboPumpRMP) Reset() {
	*x = Packet_DPTurboPumpRMP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daqpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet_DPTurboPumpRMP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet_DPTurboPumpRMP) ProtoMessage() {}

func (x *Packet_DPTurboPumpRMP) ProtoReflect() protoreflect.Message {
	mi := &file_daqpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet_DPTurboPumpRMP.ProtoReflect.Descriptor instead.
func (*Packet_DPTurboPumpRMP) Descriptor() ([]byte, []int) {
	return file_daqpb_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Packet_DPTurboPumpRMP) GetRpm() float32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

type Packet_DPEnginePRE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pressure float32 `protobuf:"fixed32,1,opt,name=pressure,proto3" json:"pressure,omitempty"`
}

func (x *Packet_DPEnginePRE) Reset() {
	*x = Packet_DPEnginePRE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_daqpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet_DPEnginePRE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet_DPEnginePRE) ProtoMessage() {}

func (x *Packet_DPEnginePRE) ProtoReflect() protoreflect.Message {
	mi := &file_daqpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet_DPEnginePRE.ProtoReflect.Descriptor instead.
func (*Packet_DPEnginePRE) Descriptor() ([]byte, []int) {
	return file_daqpb_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Packet_DPEnginePRE) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

var File_daqpb_proto protoreflect.FileDescriptor

var file_daqpb_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x64, 0x61, 0x71, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64,
	0x61, 0x71, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x04, 0x0a, 0x06, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x39, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x71, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x50, 0x76, 0x65, 0x6c, 0x6f,
	0x63, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x3f, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x61, 0x71, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x50, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x12, 0x45, 0x0a, 0x0c, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x50, 0x75, 0x6d, 0x70, 0x52, 0x4d,
	0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x61, 0x71, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x44, 0x50, 0x54, 0x75, 0x72, 0x62,
	0x6f, 0x50, 0x75, 0x6d, 0x70, 0x52, 0x4d, 0x50, 0x48, 0x00, 0x52, 0x0c, 0x74, 0x75, 0x72, 0x62,
	0x6f, 0x50, 0x75, 0x6d, 0x70, 0x52, 0x4d, 0x50, 0x12, 0x46, 0x0a, 0x0e, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x64, 0x61, 0x71, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x44, 0x50, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x50, 0x52, 0x45, 0x48, 0x00,
	0x52, 0x0e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65,
	0x1a, 0x48, 0x0a, 0x0a, 0x44, 0x50, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x65, 0x6c, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x76, 0x65,
	0x6c, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x65, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x76, 0x65, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x65, 0x6c, 0x7a, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x76, 0x65, 0x6c, 0x7a, 0x1a, 0x50, 0x0a, 0x0c, 0x44, 0x50,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x6f, 0x72, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x63, 0x6f, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x7a, 0x1a, 0x22, 0x0a, 0x0e,
	0x44, 0x50, 0x54, 0x75, 0x72, 0x62, 0x6f, 0x50, 0x75, 0x6d, 0x70, 0x52, 0x4d, 0x50, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x70, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x70, 0x6d,
	0x1a, 0x29, 0x0a, 0x0b, 0x44, 0x50, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x50, 0x52, 0x45, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x64,
	0x61, 0x71, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_daqpb_proto_rawDescOnce sync.Once
	file_daqpb_proto_rawDescData = file_daqpb_proto_rawDesc
)

func file_daqpb_proto_rawDescGZIP() []byte {
	file_daqpb_proto_rawDescOnce.Do(func() {
		file_daqpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_daqpb_proto_rawDescData)
	})
	return file_daqpb_proto_rawDescData
}

var file_daqpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_daqpb_proto_goTypes = []interface{}{
	(*Packet)(nil),                // 0: daqproto.Packet
	(*Packet_DPvelocity)(nil),     // 1: daqproto.Packet.DPvelocity
	(*Packet_DPcoordinate)(nil),   // 2: daqproto.Packet.DPcoordinate
	(*Packet_DPTurboPumpRMP)(nil), // 3: daqproto.Packet.DPTurboPumpRMP
	(*Packet_DPEnginePRE)(nil),    // 4: daqproto.Packet.DPEnginePRE
}
var file_daqpb_proto_depIdxs = []int32{
	1, // 0: daqproto.Packet.velocity:type_name -> daqproto.Packet.DPvelocity
	2, // 1: daqproto.Packet.coordinate:type_name -> daqproto.Packet.DPcoordinate
	3, // 2: daqproto.Packet.turboPumpRMP:type_name -> daqproto.Packet.DPTurboPumpRMP
	4, // 3: daqproto.Packet.enginePressure:type_name -> daqproto.Packet.DPEnginePRE
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_daqpb_proto_init() }
func file_daqpb_proto_init() {
	if File_daqpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_daqpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daqpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet_DPvelocity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daqpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet_DPcoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daqpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet_DPTurboPumpRMP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_daqpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet_DPEnginePRE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_daqpb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Packet_Velocity)(nil),
		(*Packet_Coordinate)(nil),
		(*Packet_TurboPumpRMP)(nil),
		(*Packet_EnginePressure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_daqpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_daqpb_proto_goTypes,
		DependencyIndexes: file_daqpb_proto_depIdxs,
		MessageInfos:      file_daqpb_proto_msgTypes,
	}.Build()
	File_daqpb_proto = out.File
	file_daqpb_proto_rawDesc = nil
	file_daqpb_proto_goTypes = nil
	file_daqpb_proto_depIdxs = nil
}
